ALTER TABLE routemind.dispatch_assignment_audits
    ADD COLUMN lease_id UUID;

ALTER TABLE routemind.dispatch_assignment_audits
    ADD COLUMN lease_generation BIGINT;

ALTER TABLE routemind.dispatch_assignment_audits
    ADD CONSTRAINT ck_dispatch_audit_lease_generation
    CHECK (lease_generation IS NULL OR lease_generation > 0);

CREATE TABLE routemind.dispatch_assignment_leases (
    courier_id UUID PRIMARY KEY,
    lease_id UUID NOT NULL UNIQUE,
    order_id UUID NOT NULL REFERENCES routemind.orders(id) ON DELETE CASCADE,
    decision_id VARCHAR(128) NOT NULL,
    generation BIGINT NOT NULL,
    state VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_dispatch_lease_generation CHECK (generation > 0),
    CONSTRAINT ck_dispatch_lease_state CHECK (state IN ('PROVISIONALLY_RESERVED', 'COMMITTED', 'EXPIRED', 'RELEASED')),
    CONSTRAINT ck_dispatch_lease_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_dispatch_assignment_leases_order
    ON routemind.dispatch_assignment_leases (order_id, state);

CREATE TABLE routemind.dispatch_assignment_lease_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_id UUID NOT NULL,
    courier_id UUID NOT NULL,
    order_id UUID NOT NULL,
    decision_id VARCHAR(128) NOT NULL,
    generation BIGINT NOT NULL,
    from_state VARCHAR(32),
    to_state VARCHAR(32) NOT NULL,
    reason VARCHAR(128) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_dispatch_lease_event_generation CHECK (generation > 0)
);

CREATE INDEX ix_dispatch_assignment_lease_events_courier
    ON routemind.dispatch_assignment_lease_events (courier_id, occurred_at);

COMMENT ON TABLE routemind.dispatch_assignment_leases IS
    'PostgreSQL-authoritative current assignment lease; one row per courier serializes competing decisions';
COMMENT ON TABLE routemind.dispatch_assignment_lease_events IS
    'Append-only lease transition audit for bounded recovery and incident reconstruction';
