ALTER TABLE routemind.courier_locations
    ADD COLUMN location_sequence BIGINT NOT NULL DEFAULT 1;
ALTER TABLE routemind.courier_locations
    ADD COLUMN ingested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE routemind.courier_locations
    ADD COLUMN online BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE routemind.courier_locations
    ADD CONSTRAINT ck_courier_location_sequence CHECK (location_sequence > 0);

CREATE TABLE routemind.courier_location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courier_id UUID NOT NULL,
    location_sequence BIGINT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    online BOOLEAN NOT NULL,
    CONSTRAINT uk_courier_location_history_sequence UNIQUE (courier_id, location_sequence),
    CONSTRAINT ck_courier_history_sequence CHECK (location_sequence > 0),
    CONSTRAINT ck_courier_history_latitude CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT ck_courier_history_longitude CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE INDEX ix_courier_location_history_lookup
    ON routemind.courier_location_history (courier_id, location_sequence DESC);

INSERT INTO routemind.courier_location_history
    (courier_id, location_sequence, latitude, longitude, observed_at, ingested_at, online)
SELECT courier_id, location_sequence, latitude, longitude, observed_at, ingested_at, online
FROM routemind.courier_locations;

COMMENT ON TABLE routemind.courier_location_history IS
    'Bounded durable courier location history; Redis GEO remains the rebuildable hot projection';
