CREATE TABLE routemind.orders (
    id UUID PRIMARY KEY,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_orders_status CHECK (status IN ('CREATED', 'CONFIRMED', 'ASSIGNED', 'PICKED_UP', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_audit_order CHECK (updated_at >= created_at)
);

CREATE TABLE routemind.order_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID NOT NULL REFERENCES routemind.orders(id) ON DELETE CASCADE,
    sequence_number BIGINT NOT NULL,
    from_status VARCHAR(16) NOT NULL,
    to_status VARCHAR(16) NOT NULL,
    actor VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_order_transitions_order_sequence UNIQUE (order_id, sequence_number),
    CONSTRAINT ck_order_transitions_sequence CHECK (sequence_number > 0),
    CONSTRAINT ck_order_transitions_actor CHECK (length(trim(actor)) > 0),
    CONSTRAINT ck_order_transitions_audit CHECK (occurred_at IS NOT NULL)
);

COMMENT ON TABLE routemind.orders IS 'Durable order lifecycle aggregate owned by business-api';
COMMENT ON TABLE routemind.order_transitions IS 'Immutable order lifecycle audit history';
