FROM maven:3.9.11-eclipse-temurin-17 AS build
WORKDIR /src
COPY services/business-api/pom.xml ./pom.xml
COPY services/business-api/.mvn ./.mvn
COPY services/business-api/mvnw ./mvnw
RUN mvn -B -ntp -DskipTests dependency:go-offline
COPY services/business-api/src ./src
RUN mvn -B -ntp -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /opt/routemind
COPY --from=build /src/target/business-api-0.0.1-SNAPSHOT.jar ./business-api.jar
USER 10001:10001
ENTRYPOINT ["java", "-jar", "/opt/routemind/business-api.jar"]
